### ISSUE TITLE
Multi-tenancy prep: build super-admin page

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#114]
As a super-admin, I want to be able to go to a page not accessible by Members or Librarians, so that I can edit site-wide features (e.g., member renewal policies, automated e-mails, site colors, logo, etc.).

Build the super-admin page where things like this would live and do all the back-end changes to implement. Things like:

- create a super-admin profile
- create a page where that profile goes to after log in, or have a link from the Librarian page to that page if a super-admin
- add an organizations table and rewrite queries to have "organization.id = 1" or the equivalent?

RK note: I only have a vague sense of how this would work!

A good test case would be to edit the text of an automated e-mail or pick a new logo -- we might rewrite this story to reflect that as a deliverable chunk of user value.

**Comment by rkim00** [comment]
As a super-admin, I want to be able to go to a page not accessible by Members or Librarians, so that I can edit site-wide features (e.g., member renewal policies, automated e-mails, site colors, logo, etc.).

Build the super-admin page where things like this would live and do all the back-end changes implement. Things like:
- create a super-admin profile
- add an organizations table and rewrite queries to have "organization.id = 1" or the equivalent? 

A good test case would be to edit the text of an automated e-mail or pick a new logo.

RK note: I only have vague sense of how this would work.

**Comment by KFad11** [comment]
Apartment vs Act_As_Tenant

What is the difference?

Act_As_Tenant - Uses a relational approach to isolation. Set up a relation between the individual tables we are “tenanting” and the table containing the tenants themselves. Separate tenant data is colocated with the same table.  https://github.com/ErwinM/acts_as_tenant

Apartment - Provides stronger isolation than AAT based on PostGres schema. Each tenant has their own schemas separately. Tables are duplicated between the schema and selecting the tenant is as simple as selecting that specific schema without changing the schema model. https://github.com/influitive/apartment

Pros & Cons

Pros for Apartment 
* More popular use. Downloads, Stars on GitHub, Forks, etc.
* Seems to be more actively maintained with more active forks. (ActsAsTenant explicitly no longer maintained per the ReadMe)
* Schema-based approach is robust in terms of isolation. Little to no room for data leaking. More easily query for the related data when in the separate schemas, rather than searching a shared schema for certain tenant ids.
* Easier to extract a tenants data, just need to grab the entire schema associated with that tenant.
* Easier to use a truly shared approach for scalability reasons. Instead, do a single db cluster where all the data is stored for all tenants. Each tenant gets its own db server. Improves performance. 

Cons for Apartment
* https://influitive.io/our-multi-tenancy-journey-with-postgres-schemas-and-apartment-6ecda151a21f - Schema-based approach of Apartment has been actively rejected by original authors. They’ve switched to the relational approach themselves.
    * Repeated migrations affect performance (slow deployments)
    * They suggested that the schema-based approach causes run-time db problems. Spending on the resources was higher needing more servers. Not proven but felt strongly for
    * ActiveRecord memory bloat became an issue. Storing multiple copies of the schema in memory, as you add tenants the app used more memory. 
    * Duplicated identifiers across each table. tool.id(1) is a hammer in one db, a saw in another. 
* The original implementation isn’t compatible with Rails 6, there is a fork that does. 

Pros for Act_As_Tenant
* Relational approach will work with any SQL db, not just PostGres.
* Somewhat more traditional, more broadly understood lends to being more easily contributed to. 	
	
Cons for Act_As_Tenant
* Less popular/used
* Not maintained as much
* Requires schema changes 
* Requires actively considering the tenant association in the schema of each table.

Conclusion

Weighing all of the above, we’re leaning more heavily towards using the Act_As_Tenant gem. 

@rkim00 @pollygee @jim - Does that analysis look OK to everyone? Anything to add from your perspective?

**Comment by KFad11** [comment]
In order to test subdomain tenant routing locally, we recommend creating real dns records. `*.local.chicagotoollibrary.org A 127.0.0.1`. This would work for devs to test as long as they have an internet connection. Anyone with more complex requirements such as working offline could use dnsmasq but we’d like not to include that as a hard requirement to simplify the onboarding of new devs.

**Comment by KFad11** [comment]
As far as representing the individual tenants, were going to go with `Library`

**Comment by jim** [comment]
The issues stemming from apartment's use of schemas pretty much removes it as an option, so `acts_as_tenant` seems like a good way to go.

I can setup the DNS for this tonight. Long-term, we might want to use a different URL, but it seems worthwhile to get this going for the short term.

**Comment by jim** [comment]
@KFad11 I added that DNS record, so please test things out on your machine and let me know if there are any issues!

**Comment by neildecapia** [comment]
@jim This is working great. Thanks!
