### ISSUE TITLE
UX: audit admin pages to make sure things are mobile-useable

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#200]
These probably don't need to be beautiful on mobile, since admin activities are usually done on a computer, but everything should be useable, for the occasional do-it-on-the-phone emergency. And/or if admins want to use tablets.

**Comment by christinaatai** [comment]
This issue is general, so I just tackled a few UX/UI elements (listed and shown below).

This PR tackles four UX/UI elements:

**1. Made item header responsive**

<img width="900" alt="Screen Shot 2020-09-25 at 10 15 54 AM" src="https://user-images.githubusercontent.com/42459486/94278313-a6be2a80-ff18-11ea-9926-2c2828c63cd7.png">

**2. Made item header consistent**

<img width="1492" alt="Screen Shot 2020-09-25 at 10 20 18 AM" src="https://user-images.githubusercontent.com/42459486/94278428-ca817080-ff18-11ea-9ff5-42c3ef2ca686.png">

**3. Added placeholder text for empty details**

<img width="1087" alt="Screen Shot 2020-09-25 at 10 21 55 AM" src="https://user-images.githubusercontent.com/42459486/94278676-1cc29180-ff19-11ea-820a-85ca382b107f.png">

**4. Fixed name in verifying member notification so that if there is no preferred name, it would use the full name**

<img width="1559" alt="Screen Shot 2020-09-25 at 10 40 19 AM" src="https://user-images.githubusercontent.com/42459486/94280702-b55a1100-ff1b-11ea-8826-ef7e8fbb1cce.png">

**Comment by christinaatai** [comment]
I have opened a new issue ([Issue 244](https://github.com/rubyforgood/circulate/issues/244)) and will close this one.
