### ISSUE TITLE
Change debugging configuration

### ISSUE THREAD

**Issue by sboligitz** [rubyforgood/circulate#241]
There was a configuration that wasn't set up in the best way, and it was making it difficult to run debugging tools for developers.

We've updated that configuration!

**Comment by jim** [comment]
@sboligitz or @terryfinn Was this handled by #239 ?

**Comment by terryfinn** [comment]
Yes.

On October 3, 2020, Tom Scott <notifications@github.com> wrote:
> @sboligitz <https://github.com/sboligitz> or @terryfinn
> <https://github.com/terryfinn> Was this handled by #239
> <https://github.com/rubyforgood/circulate/pull/239> ?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rubyforgood/circulate/issues/241#issuecomment-
703160512>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAEOSUKAXMTKHIDLXO46753SI6CE7ANCNFSM4RZQPR2A>.

**Comment by jim** [comment]
Great! Closed by #239.
