### ISSUE TITLE
Figure out why placing a hold doesn't seem to work on Staging.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#255]
Currently when a logged-in member places a hold on an item Staging (https://circulate-staging.herokuapp.com/), the hold doesn't seem to be created and the member gets redirected to a 404-ish page. Would be great to (1) diagnose and (2) fix.

may be related to #258

**Comment by terryfinn** [comment]
@rkim00 This is related to the feature power added last week? I have some ideas as to what could cause this. Who can I work with the view logs or exceptions in he staging environment?

**Comment by terryfinn** [comment]
@rkim00 I just tried to reproduce this locally, and I am unable to do so. It is possible this is a data issue in staging. Logs, exceptions, or a copy the the staging database would be helpful in debugging this.

**Comment by jim** [comment]
@rkim00 @terryfinn We had hit the database row limit on staging, which was breaking things in a lot of weird ways. That problem is resolved now, so we should test to see if this issue is still valid.

**Comment by jim** [comment]
FWIW I was just able to put something on hold on staging, so I think this is resolved now.

**Comment by terryfinn** [comment]
I think it is a data issue, well that is my best guess.

On October 4, 2020, Tom Scott <notifications@github.com> wrote:
> FWIW I was just able to put something on hold on staging, so I think

> this is resolved now.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rubyforgood/circulate/issues/255#issuecomment-
703270081>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAEOSUPJQ66KD3ALBQZMAVTSJCGQRANCNFSM4SAOS2EQ>.

**Comment by rkim00** [comment]
Yes, looks fixed. Closing.
