### ISSUE TITLE
Add reminder text under "Select a time for the appointment"

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#606]
On Schedule Appointments page, add text underneath "Select a time for the appointment"
https://circulate-staging.herokuapp.com/account/appointments/new

"Don't worry if you arrive a little bit early or late, as long as it's within the library's open hours."

![Screenshot 2021-08-31 182200](https://user-images.githubusercontent.com/3331/131588321-cfc96c06-e5b4-4471-84f4-9f0b5fb1e95f.png)

**Comment by rkim00** [comment]
Hey @CTLvivek , thanks for this. It may be that @jim has context on this already, but if not, it may be useful for these and other comments for you to identify the specific problem that is being resolved, and/or the benefit that we hope will be achieved, so that we can appropriately prioritize. E.g., "we're experiencing that people are very stressed about making their appointment time, and are calling the library in order to let us know that they'll be late, which is more overhead for staff. To decrease user anxiety and librarian overhead, we'd like to...."

If it helps you, in lots of Agile story-writing, this is described by the formula, "AS ____ I WANT ____ SO THAT____." "As a user, I want know that appointment slots are not hard and fast, so that I can not stress about my appointment time."

It's also fine just to dump notes and half-finished ideas here—I intend this column to be a bit messy. But these are the sorts of details that I look for in order to flesh out a story, and the sorts of information that I would typically try to gather before moving into the "Ready to be worked on" column.

**Comment by CTLvivek** [comment]
Thanks for the extra guidance, Richard. I can definitely do that in the future!  I'll make sure that my github issues have the necessary detail. Beyond that my plan is to always leave some explanation in Slack where more people are involved in the discussion and also to be available to help with prioritization as needed. 

In the context of this specific issue, it is basically exactly what you described -> decreasing stress of the users and the subsequent overhead for volunteer librarians.

**Comment by stephanieminn** [comment]
👋 working on this in https://github.com/rubyforgood/circulate/pull/642
